// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type BookInfo struct {
	Metadata *BookMetadata `json:"metadata"`
	Reviews  *BookReviews  `json:"reviews"`
}

type BookMetadata struct {
	Title          *string `json:"title"`
	PublishingDate *string `json:"publishingDate"`
	NumberOfPages  *int    `json:"numberOfPages"`
}

type BookReviews struct {
	NumberOfRatings *int     `json:"NumberOfRatings"`
	NumberOfReviews *int     `json:"NumberOfReviews"`
	AverageRating   *float64 `json:"AverageRating"`
}
